### ISSUE TITLE
make the data source name unique

### ISSUE THREAD

**Issue by knktc** [EverythingMe/redash#277]
I found that I can add multiple datasource with a same name. Maybe we should make this field unique.

**Comment by lenguyenthedat** [comment]
+1

Currently we can add data sources with the same name, but we can't properly delete them:
    
    ubuntu@ip-172-31-17-246:/opt/redash/current$ sudo -u redash bin/run ./manage.py ds list
    [2015-03-20 07:00:42,967][PID:29756][WARNING][google_oauth] No Google Apps domain defined, all Google accounts allowed.
    Id: 2
    Name: my-data-source
    Type: pg
    Options: {---deleted---}
    --------------------
    Id: 3
    Name: my-data-source
    Type: pg
    Options: {---deleted---}

    ubuntu@ip-172-31-17-246:/opt/redash/current$ sudo -u redash bin/run ./manage.py ds delete "my-data-source"
    [2015-03-20 07:06:40,346][PID:29798][WARNING][google_oauth] No Google Apps domain defined, all Google accounts allowed.
    Deleting data source: my-data-source (id=2)
    [2015-03-20 07:06:40,450][PID:29798][ERROR][peewee] DELETE FROM "data_sources" WHERE ("id" = %s) [2]
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 351, in execute_sql
        cursor.execute(sql, params or ())
    IntegrityError: update or delete on table "data_sources" violates foreign key constraint "query_results_data_source_id_fkey" on table "query_results"
    DETAIL:  Key (id)=(2) is still referenced from table "query_results".

    Traceback (most recent call last):
      File "/opt/redash/redash.0.6.0.b722/manage.py", line 49, in <module>
        manager.run()
      File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 405, in run
        result = self.handle(sys.argv[0], sys.argv[1:])
      File "/usr/local/lib/python2.7/dist-packages/flask_script/__init__.py", line 384, in handle
        return handle(app, *positional_args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/flask_script/commands.py", line 145, in handle
        return self.run(*args, **kwargs)
      File "/opt/redash/redash.0.6.0.b722/redash/cli/data_sources.py", line 95, in delete
        data_source.delete_instance()
      File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3937, in delete_instance
        return self.delete().where(self._pk_expr()).execute()
      File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2694, in execute
        return self.database.rows_affected(self._execute())
      File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2243, in _execute
        return self.database.execute_sql(sql, params, self.require_commit)
      File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 358, in execute_sql
        self.commit()
      File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2732, in __exit__
        reraise(new_type, new_type(*exc_value.args), traceback)
      File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 351, in execute_sql
        cursor.execute(sql, params or ())
    peewee.IntegrityError: update or delete on table "data_sources" violates foreign key constraint "query_results_data_source_id_fkey" on table "query_results"
    DETAIL:  Key (id)=(2) is still referenced from table "query_results".

**Comment by arikfr** [comment]
Implemented in #398.
